package com.cram_era.backend.entities;

import java.sql.Timestamp;

// represents a row in the database table, can refer to Jolin's SQL for this.
// This is for storing the user into the database
// userName and userEmail will be provided by the person, userId and createdAt will be generated by the system (mySQL).
public class User {
    private int userId;
    private String userName;
    private String userEmail;
    private Timestamp createdAt;

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }
}
