package com.cram_era.backend.entities;

import jakarta.persistence.*;
import java.time.LocalDateTime;

// represents a row in the database table, can refer to Jolin's SQL for this.
// This is for storing the user into the database
// userName and userEmail will be provided by the person, userId and createdAt will be generated by the system (mySQL).

@Entity
@Table(name = "users")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "users_ID")
    private Integer userId;

    @Column(name = "user_name", length = 20)
    private String userName;

    @Column(name = "user_email", length = 40)
    private String userEmail;

    @Column(name = "created_at", insertable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "password_hash")
    private String passwordHash;

    public int getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getPasswordHash() { return passwordHash; }

    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }
}
